ALTER TABLE "user_preferences"
  ADD COLUMN "cultureWeight" INTEGER NOT NULL DEFAULT 80,
  ADD COLUMN "foodWeight" INTEGER NOT NULL DEFAULT 80,
  ADD COLUMN "adventureWeight" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN "natureWeight" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN "relaxationWeight" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN "travelPace" TEXT NOT NULL DEFAULT 'moderate',
  ADD COLUMN "budgetLevel" TEXT NOT NULL DEFAULT 'moderate';
